# For more details on the format and content
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.9.16
  - nodejs=22
  - pip=24.3.1
  - tzdata
  - pip:
      # for robot framework
      - robotframework==7.2.2
      - robotframework-browser==19.3.0
      - robotframework-tidy

      # Python dependencies
      - beautifulsoup4

      # Google Auth
      - google-auth
      - google-auth-oauthlib
      
      # Environment management
      - python-dotenv

rccPostInstall:
  - rfbrowser init
