# For more details on the format and content
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.12.3
  - nodejs=22
  - pip=24.3.1
  - tzdata
  - pip:
      # for robot framework
      - robotframework==7.3.2
      - robotframework-browser==19.12.0
      - robotframework-requests==0.9.7
      - robotframework-pabot==5.1.0

      # Environment management
      - python-dotenv==1.2.1

      # Code Quality and Linting Tools
      - robotframework-robocop==6.13.0
      - ruff==0.14.7

rccPostInstall:
  - rfbrowser init
