# For more details on the format and content
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.12.3
  - nodejs=22
  - pip=24.3.1
  - tzdata
  - pip:
      # for robot framework
      - robotframework==7.3.2
      - robotframework-browser==19.6.2
      - robotframework-requests
      - robotframework-pabot==4.3.2

      # Python dependencies
      - beautifulsoup4

      # Google Auth
      - google-auth
      - google-auth-oauthlib

      # Environment management
      - python-dotenv

      # Code Quality and Linting Tools
      - robotframework-robocop>=6.0.0
      - ruff>=0.1.0

rccPostInstall:
  - rfbrowser init
