name: Varaamo Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Select which test suite to run'
        required: true
        default: 'All'
        type: choice
        options:
          - All
          - Tests_user_desktop_FI
          - Tests_user_mobile_iphone_FI
          - Tests_user_mobile_android_FI
          - Tests_users_with_admin_desktop
          - Tests_admin_desktop_FI

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    steps:
      # 1. Checkout the repository so that the Dockerfile, TestSuites, and Reports folders are available.
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Build the Docker image from your Dockerfile.
      - name: Build Docker Image
        run: docker build --no-cache -t robotframework-tests .

      # Ensure the Reports directory has the correct permissions
      - name: Set Permissions for Reports Directory
        run: |
          mkdir -p "${{ github.workspace }}/Reports"
          chmod 777 "${{ github.workspace }}/Reports"

      # 3. Run the Docker container to execute your Robot Framework tests.
      #    Mount the "TestSuites" folder to /opt/robotframework/tests 
      #    and the "Reports" folder to /opt/robotframework/reports.
      #    Using the '--nostatusrc' flag to ignore failed runs

      - name: Run Selected Test Suite
        run: |
          TEST_SUITE=""
          if [ "${{ github.event.inputs.test_suite }}" == "Tests_user_desktop_FI" ]; then
            TEST_SUITE="/opt/robotframework/tests/Tests_user_desktop_FI.robot"
          elif [ "${{ github.event.inputs.test_suite }}" == "Tests_user_mobile_iphone_FI" ]; then
            TEST_SUITE="/opt/robotframework/tests/Tests_user_mobile_iphone_FI.robot"
          elif [ "${{ github.event.inputs.test_suite }}" == "Tests_user_mobile_android_FI" ]; then
            TEST_SUITE="/opt/robotframework/tests/Tests_user_mobile_android_FI.robot"
          elif [ "${{ github.event.inputs.test_suite }}" == "Tests_users_with_admin_desktop" ]; then
            TEST_SUITE="/opt/robotframework/tests/Tests_users_with_admin_desktop.robot"
          elif [ "${{ github.event.inputs.test_suite }}" == "Tests_admin_desktop_FI" ]; then
            TEST_SUITE="/opt/robotframework/tests/Tests_admin_desktop_FI.robot"
          elif [ "${{ github.event.inputs.test_suite }}" == "All" ] || [ -z "${{ github.event.inputs.test_suite }}" ]; then
            # Run all tests if "all" is selected or if running via push/PR (no input)
            TEST_SUITE="/opt/robotframework/tests"
          fi

          docker run --rm \
            -e ACCESS_TOKEN \
            -e REFRESH_TOKEN \
            -e CLIENT_ID \
            -e CLIENT_SECRET \
            -v "${{ github.workspace }}/TestSuites:/opt/robotframework/tests" \
            -v "${{ github.workspace }}/Reports:/opt/robotframework/reports" \
            robotframework-tests robot --outputdir /opt/robotframework/reports --nostatusrc $TEST_SUITE
            
      # 4. Upload the generated test reports as artifacts.
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: Reports/
