name: Varaamo tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    steps:
      # 1. Checkout the repository so that the Dockerfile, TestSuites, and Reports folders are available.
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Build the Docker image from your Dockerfile.
      - name: Build Docker Image
        run: docker build --no-cache -t robotframework-tests .

      # 3. Run the Docker container to execute your Robot Framework tests.
      #    Mount the "TestSuites" folder to /opt/robotframework/tests 
      #    and the "Reports" folder to /opt/robotframework/reports.
      - name: Run Robot Framework Tests in Docker
        run: |
          docker run --rm \
            -e ACCESS_TOKEN \
            -e REFRESH_TOKEN \
            -e CLIENT_ID \
            -e CLIENT_SECRET \
            -v "${{ github.workspace }}/TestSuites:/opt/robotframework/tests" \
            -v "${{ github.workspace }}/Reports:/opt/robotframework/reports" \
            robotframework-tests

      # 4. Upload the generated test reports as artifacts.
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: Reports/
