name: Varaamo Robot Framework Tests

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: "Select which test suite to run"
        required: true
        default: "All"
        type: choice
        options:
          - Smoke
          - All
          - Tests_user_desktop_FI
          - Tests_user_mobile_iphone_FI
          - Tests_user_mobile_android_FI
          - Tests_users_with_admin_desktop
          - Tests_admin_desktop_FI

jobs:
  smoke-tests:
    name: 🔥 Smoke Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.test_suite == 'Smoke' || github.event.inputs.test_suite == 'All' }}
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build --no-cache -t robotframework-tests .

      - name: Prepare reports folder
        run: |
          mkdir -p "${{ github.workspace }}/Reports"
          chmod 777 "${{ github.workspace }}/Reports"

      - name: Run Smoke Tests
        run: |
          docker run --rm \
            -e ACCESS_TOKEN \
            -e REFRESH_TOKEN \
            -e CLIENT_ID \
            -e CLIENT_SECRET \
            -v "${{ github.workspace }}/TestSuites:/opt/robotframework/tests" \
            -v "${{ github.workspace }}/Reports:/opt/robotframework/reports" \
            robotframework-tests robot \
              --outputdir /opt/robotframework/reports \
              --include smoke \
              /opt/robotframework/tests/Tests_user_desktop_FI.robot \
              /opt/robotframework/tests/Tests_admin_desktop_FI.robot

      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ github.job }}
          path: Reports/

  full-via-smoke:
    name: ✅ Full Test Suite
    needs: smoke-tests
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.test_suite == 'All' && needs.smoke-tests.result == 'success' }}
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v3

      - name: Determine test suite
        id: determine-test-suite
        run: |
          # Only "All" ever reaches here
          SUITE_PATH="/opt/robotframework/tests"
          echo "suite_path=$SUITE_PATH" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build --no-cache -t robotframework-tests .

      - name: Prepare reports folder
        run: |
          mkdir -p "${{ github.workspace }}/Reports"
          chmod 777 "${{ github.workspace }}/Reports"

      - name: Run Full Suite
        run: |
          docker run --rm \
            -e ACCESS_TOKEN \
            -e REFRESH_TOKEN \
            -e CLIENT_ID \
            -e CLIENT_SECRET \
            -v "${{ github.workspace }}/TestSuites:/opt/robotframework/tests" \
            -v "${{ github.workspace }}/Reports:/opt/robotframework/reports" \
            robotframework-tests robot \
              --outputdir /opt/robotframework/reports \
              --nostatusrc \
              ${{ steps.determine-test-suite.outputs.suite_path }}

      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ github.job }}
          path: Reports/

  full-direct:
    name: ✅ Full Test Suite (direct)
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.test_suite != 'All' && github.event.inputs.test_suite != 'Smoke' }}
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v3

      - name: Determine test suite
        id: determine-test-suite
        run: |
          case "${{ github.event.inputs.test_suite }}" in
            Tests_user_desktop_FI)          SUITE_PATH="/opt/robotframework/tests/Tests_user_desktop_FI.robot" ;;
            Tests_user_mobile_iphone_FI)    SUITE_PATH="/opt/robotframework/tests/Tests_user_mobile_iphone_FI.robot" ;;
            Tests_user_mobile_android_FI)   SUITE_PATH="/opt/robotframework/tests/Tests_user_mobile_android_FI.robot" ;;
            Tests_users_with_admin_desktop) SUITE_PATH="/opt/robotframework/tests/Tests_users_with_admin_desktop.robot" ;;
            Tests_admin_desktop_FI)         SUITE_PATH="/opt/robotframework/tests/Tests_admin_desktop_FI.robot" ;;
          esac
          echo "suite_path=$SUITE_PATH" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build --no-cache -t robotframework-tests .

      - name: Prepare reports folder
        run: |
          mkdir -p "${{ github.workspace }}/Reports"
          chmod 777 "${{ github.workspace }}/Reports"

      - name: Run Selected Test Suite
        run: |
          docker run --rm \
            -e ACCESS_TOKEN \
            -e REFRESH_TOKEN \
            -e CLIENT_ID \
            -e CLIENT_SECRET \
            -v "${{ github.workspace }}/TestSuites:/opt/robotframework/tests" \
            -v "${{ github.workspace }}/Reports:/opt/robotframework/reports" \
            robotframework-tests robot \
              --outputdir /opt/robotframework/reports \
              --nostatusrc \
              ${{ steps.determine-test-suite.outputs.suite_path }}

      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ github.job }}
          path: Reports/
